-- Collaboration, in-app notifications and attachments.
-- Run this once in the Supabase SQL Editor after the earlier migrations.
-- Reminders are created by the dashboard when the assignee next opens it;
-- for scheduled email/push delivery, connect this table to a cron/Edge Function.

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  assignment_id bigint references public.assignments(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  reminder_key text,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (recipient_id, assignment_id, type, reminder_key)
);

create table if not exists public.assignment_attachments (
  id bigint generated by default as identity primary key,
  assignment_id bigint not null references public.assignments(id) on delete cascade,
  uploaded_by uuid not null references public.profiles(id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  file_size bigint not null default 0,
  mime_type text,
  created_at timestamptz not null default now()
);

alter table public.notifications enable row level security;
alter table public.assignment_attachments enable row level security;

create or replace function public.can_access_assignment(target_id bigint) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.assignments a
    where a.id = target_id and (
      public.current_role() = 'Admin'
      or a.assigned_to::text = auth.uid()::text
      or a.assigned_by::text = auth.uid()::text
      or (public.current_role() = 'Manager' and a.assigned_to::text in (
        select id::text from public.profiles where team_id in (select public.my_team_ids())
      ))
      or (public.current_role() = 'Employee' and a.assigned_to::text in (
        select id::text from public.profiles where supervisor_id = auth.uid()
      ))
    )
  );
$$;

drop policy if exists notifications_select_own on public.notifications;
drop policy if exists notifications_insert_own on public.notifications;
drop policy if exists notifications_insert_visible on public.notifications;
drop policy if exists notifications_update_own on public.notifications;
create policy notifications_select_own on public.notifications for select using (recipient_id = auth.uid());
create policy notifications_insert_visible on public.notifications for insert with check (
  recipient_id = auth.uid()
  or (
    assignment_id is not null
    and public.can_access_assignment(assignment_id)
    and recipient_id::text = (select assigned_to::text from public.assignments where id = assignment_id)
  )
);
create policy notifications_update_own on public.notifications for update using (recipient_id = auth.uid()) with check (recipient_id = auth.uid());

drop policy if exists attachments_select_visible on public.assignment_attachments;
drop policy if exists attachments_insert_visible on public.assignment_attachments;
drop policy if exists attachments_delete_own on public.assignment_attachments;
create policy attachments_select_visible on public.assignment_attachments for select using (public.can_access_assignment(assignment_id));
create policy attachments_insert_visible on public.assignment_attachments for insert with check (uploaded_by = auth.uid() and public.can_access_assignment(assignment_id));
create policy attachments_delete_own on public.assignment_attachments for delete using (uploaded_by = auth.uid());

insert into storage.buckets (id, name, public, file_size_limit)
values ('assignment-files', 'assignment-files', false, 10485760)
on conflict (id) do update set public = false, file_size_limit = 10485760;

drop policy if exists assignment_files_read on storage.objects;
drop policy if exists assignment_files_upload on storage.objects;
drop policy if exists assignment_files_delete on storage.objects;
create policy assignment_files_read on storage.objects for select using (
  bucket_id = 'assignment-files' and public.can_access_assignment(((storage.foldername(name))[1])::bigint)
);
create policy assignment_files_upload on storage.objects for insert with check (
  bucket_id = 'assignment-files'
  and auth.uid() is not null
  and public.can_access_assignment(((storage.foldername(name))[1])::bigint)
);
create policy assignment_files_delete on storage.objects for delete using (
  bucket_id = 'assignment-files' and owner_id::text = auth.uid()::text
);
